#pragma once

#include "PhysicsSimulator.hpp"
#include <string>
#include <vector>

namespace pathfinder {

    class GDR2Exporter {
    public:
        struct GDR2Replay {
            std::string author = "AI Pathfinder";
            std::string description = "Auto-generated by AI Pathfinder mod";
            double duration = 0.0;
            int fps = 240;
            int levelID = 0;
            std::string levelName;
            std::vector<FrameData> frames;
        };

        static std::string serialize(const GDR2Replay& replay);
        static bool saveToFile(const GDR2Replay& replay, const std::string& filepath);
        static std::string getDefaultFilename(const std::string& levelName, int levelID);
    };

} // namespace pathfinder